<a href="https://colab.research.google.com/github/manali-star/ML_From_Scratch/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('Employee.csv')
df.shape

(148, 6)

In [ ]:
df

     Company   Age  Salary     Place Country  Gender
0        TCS  20.0     NaN   Chennai   India       0
1    Infosys  30.0     NaN    Mumbai   India       0
2        TCS  35.0  2300.0  Calcutta   India       0
3    Infosys  40.0  3000.0     Delhi   India       0
4        TCS  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
143      TCS  33.0  9024.0  Calcutta   India       1
144  Infosys  22.0  8787.0  Calcutta   India       1
145  Infosys  44.0  4034.0     Delhi   India       1
146      TCS  33.0  5034.0    Mumbai   India       1
147  Infosys  22.0  8202.0    Cochin   India       0

[148 rows x 6 columns]

In [ ]:
#delete duplicate rows
df.duplicated().sum()

np.int64(4)

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(144, 6)

In [ ]:
df.reset_index(inplace=True)
df.drop('index',axis=1,inplace=True)
df

             Company   Age  Salary     Place Country  Gender
0                TCS  20.0     NaN   Chennai   India       0
1            Infosys  30.0     NaN    Mumbai   India       0
2                TCS  35.0  2300.0  Calcutta   India       0
3            Infosys  40.0  3000.0     Delhi   India       0
4                TCS  23.0  4000.0    Mumbai   India       0
..               ...   ...     ...       ...     ...     ...
139  Infosys Pvt Lmt  22.0  8202.0    Mumbai   India       0
140              TCS  33.0  9024.0  Calcutta   India       1
141          Infosys  44.0  4034.0     Delhi   India       1
142              TCS  33.0  5034.0    Mumbai   India       1
143          Infosys  22.0  8202.0    Cochin   India       0

[144 rows x 6 columns]

In [ ]:
df.head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  136 non-null    object
 1   Age      127 non-null    float64
 2   Salary   121 non-null    float64
 3   Place    130 non-null    object
 4   Country  144 non-null    object
 5   Gender   144 non-null    int64
dtypes: float64(2), int64(1), object(3)
memory usage: 6.9+ KB

In [ ]:
df.colums

AttributeError: 'DataFrame' object has no attribute 'coloums'